# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_auto_20170522_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('man', 'Man'), ('woman', 'Woman'), ('трап', 'Трап')], max_length=40, verbose_name='Gender'),
        ),
    ]
