# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_auto_20171221_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('мужчина', 'Мужчина'), ('женщина', 'Женщина'), ('трап', 'Трап')], max_length=40, verbose_name='Gender'),
        ),
    ]
