# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_auto_20171221_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='userprofiles/avatars', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='completion_level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Процент заполнения профиля'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_is_verified',
            field=models.BooleanField(default=False, verbose_name='Email верифицирован'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('мужчина', 'Мужчина'), ('женщина', 'Женщина'), ('трап', 'Трап')], max_length=40, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='personal_info_is_completed',
            field=models.BooleanField(default=False, verbose_name='Персональная информация заполнена'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Телефон'),
        ),
    ]
