# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-15 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, max_length=200, verbose_name='Транслит'),
        ),
    ]
