# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autist', '0008_auto_20171220_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('мужчина', 'Мужчина'), ('женщина', 'Женщина'), ('трап', 'Трап')], max_length=40, verbose_name='Gender')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='userprofiles/avatars', verbose_name='Avatar')),
                ('completion_level', models.PositiveSmallIntegerField(default=0, verbose_name='Profile completion percentage')),
                ('email_is_verified', models.BooleanField(default=False, verbose_name='Email is verified')),
                ('personal_info_is_completed', models.BooleanField(default=False, verbose_name='Personal info completed')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'User profile',
                'verbose_name_plural': 'User profiles',
                'verbose_name': 'User profile',
            },
        ),
    ]
