# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0010_auto_20171221_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
