# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-18 11:38
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0011_addproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='VkNewPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='addproject',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назние проекта'),
        ),
    ]
