# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-19 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0015_remove_addproject_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VkNewPost',
            new_name='SocialPost',
        ),
    ]
