# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-19 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0016_auto_20180119_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialPost',
        ),
    ]
