# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-19 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0018_addproject_publications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproject',
            old_name='publications',
            new_name='accounts',
        ),
    ]
