# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-19 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('autist', '0019_auto_20180119_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproject',
            name='accounts',
        ),
        migrations.AddField(
            model_name='addproject',
            name='account',
            field=models.ManyToManyField(to='socialaccount.SocialAccount', verbose_name='Выберите аккаунты'),
        ),
    ]
