# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0021_remove_addproject_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproject',
            name='account',
            field=models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('b', 'big')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
