# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0023_auto_20180120_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='account',
            field=models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('b', 'big')], max_length=1),
        ),
    ]
