# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0026_addproject_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproject',
            name='account',
        ),
    ]
