# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0029_auto_20180122_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('categories', models.ManyToManyField(to='autist.Category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autist.City')),
            ],
        ),
        migrations.AlterField(
            model_name='addproject',
            name='connected_accounts',
            field=models.ManyToManyField(blank=True, null=True, to='socialaccount.SocialAccount', verbose_name='Присоединенные аккаунты'),
        ),
        migrations.AddField(
            model_name='category',
            name='available_in',
            field=models.ManyToManyField(to='autist.City'),
        ),
    ]
