# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0031_auto_20180122_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='available_in',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='addproject',
            name='connected_accounts',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
