# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('autist', '0032_auto_20180122_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproject',
            name='connected_accounts',
            field=models.ManyToManyField(blank=True, to='socialaccount.SocialAccount', verbose_name='Присоединенные аккаунты'),
        ),
    ]
