# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0033_addproject_connected_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('1', 'red'), ('2', 'blue'), ('3', 'black')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='addproject',
            name='connected_accounts',
        ),
        migrations.AddField(
            model_name='addproject',
            name='category',
            field=models.ManyToManyField(to='autist.Category'),
        ),
    ]
