# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0034_auto_20180122_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='category',
            field=models.ManyToManyField(to='autist.Category', verbose_name='Категория'),
        ),
    ]
