# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0035_auto_20180122_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproject',
            old_name='author',
            new_name='user',
        ),
    ]
