# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('autist', '0036_auto_20180122_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproject',
            name='category',
        ),
        migrations.AddField(
            model_name='addproject',
            name='accounts',
            field=models.ManyToManyField(to='socialaccount.SocialAccount', verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
