# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0005_auto_20180122_1207'),
        ('autist', '0041_auto_20180122_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproject',
            name='accounts',
            field=models.ManyToManyField(blank=True, to='socialaccount.SocialAccount'),
        ),
    ]
