# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0042_addproject_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='accounts',
            field=models.ManyToManyField(to='socialaccount.SocialAccount', verbose_name='Подключенные аккаунты к учетной записи'),
        ),
    ]
