# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-26 15:42
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0043_auto_20180122_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInVk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
            ],
        ),
    ]
