# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-27 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0044_postinvk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vk_groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Название группы')),
                ('gid', models.CharField(max_length=1000, verbose_name='ID группы')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрытая группа')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Пользователь является администратором')),
            ],
            options={
                'verbose_name': 'Группа Вконтакте',
                'verbose_name_plural': 'Группы Вконтакте',
            },
        ),
        migrations.CreateModel(
            name='Vk_posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=1000, verbose_name='Страница/группа')),
                ('text', tinymce.models.HTMLField(blank=True, verbose_name='Текст записи')),
                ('date', models.DateTimeField(blank=True, verbose_name='Дата публикации')),
            ],
        ),
        migrations.DeleteModel(
            name='PostInVk',
        ),
    ]
