# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-27 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0045_auto_20180127_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vk_posts',
            name='group',
        ),
    ]
