# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-27 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0046_remove_vk_posts_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vk_posts',
            new_name='VkPosts',
        ),
    ]
