# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-27 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0047_auto_20180127_1414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vk_groups',
        ),
    ]
