# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0051_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100, verbose_name='Выберите задание')),
                ('link', models.URLField(max_length=100, verbose_name='Ссылка')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('coasts', models.CharField(max_length=100, verbose_name='Цена')),
            ],
        ),
    ]
