# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-23 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autist', '0056_auto_20180323_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=250, unique_for_date='published_date', verbose_name='Alias'),
        ),
    ]
